# vim:ft=ansible:
- name: Cloning bash it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: ~/.bash_it
    clone: yes
    update: yes

- name: Removing existing .bashrc.bak
  file:
    path: ~/.bashrc.bak
    state: absent

- name: Executing the bash it
  command: ~/.bash_it/install.sh 

- name: Adding alias to bashit
  blockinfile:
    block: "{{ lookup('file', '../../../dotfiles/_unix-alias') }}"
    dest: "~/.bashrc"
    backup: yes

- name: Install a bashit powerline theme
  lineinfile:
    path: ~/.bashrc
    regexp: '^export BASH_IT_THEME='
    line: 'export BASH_IT_THEME="powerline"'

- name: Adding bashit completion on ssh
  shell: . ~/.bash_it/bash_it.sh enable completion ssh
