# vim:ft=ansible:
# tasks file for simc-builder
- name: Install the build essential
  become: yes
  package:
    name: build-essential
    state: latest

- name: Install libssl-dev
  become: yes
  package:
    name: libssl-dev
    state: latest

- name: Clone simc
  git:
    repo: https://github.com/simulationcraft/simc.git
    dest: ~/simc
    clone: yes
    update: yes

- name: Make the application
  command: make OPENSSL=1 optimized
  args:
    chdir: ~/simc/engine/
