# vim:ft=ansible:
- name: Cloning bash it
  git:
    repo: https://github.com/Bash-it/bash-it.git
    dest: ~/.bash_it
    clone: yes
    update: yes

- name: Removing existing .bashrc.bak
  file:
    path: ~/.bashrc.bak
    state: absent

- name: Executing the bash it
  command: ~/.bash_it/install.sh 

- name: clone dotfiles
  git:
    repo: https://github.com/elaurendeau/dotfiles.git
    dest: ~/dotfiles
    clone: yes
    update: yes

- name: Adding alias to bashit
  blockinfile:
    block: ~/dotfiles/_unix-alias
    dest: ~/.bashrc
    backup: yes

- name: Install a bashit powerline theme
  lineinfile:
    path: ~/.bashrc
    regexp: '^export BASH_IT_THEME='
    line: 'export BASH_IT_THEME="powerline"'
