# vim:ft=ansible:
# tasks file for vim
- name: Install and configure vim
  become: yes
  package:
    name: vim
    state: latest

- name: Clone vim vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    clone: yes
    update: yes

- name: clone dotfiles
  git:
    repo: https://github.com/elaurendeau/dotfiles.git
    dest: ~/dotfiles
    clone: yes
    update: yes

- name: copy vimrc
  copy:
    src: ~/dotfiles/_vimrc
    remote_src: yes
    dest: ~/

- name: Install all plugins
  command: vim +PluginInstall +qall
